### ISSUE TITLE
support for Zenoss 3.2.1

### ISSUE THREAD

**Issue by paericksen** [jcurry/ZenPacks.community.A10#1]
Would it be possible to make this zenpack work on Zenoss Core 3.2.1?

**Comment by jcurry** [comment]
Might be possible.  Do you have a test environment with some A10 kit if 
I can cut you a version for 3.2.1??
Cheers,
Jane

On 06/05/15 18:02, Andy Ericksen wrote:

> Would it be possible to make this zenpack work on Zenoss Core 3.2.1?
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/jcurry/ZenPacks.community.A10/issues/1.

## 

Zenoss Master, Tivoli Certified Consultant & Instructor
Skills 1st Limited, 2 Cedar Chase, Taplow, Bucks, SL6 0EU, UK.
Registered in England & Wales, Company No. 3458854.
Tel: +44 (0)1628 782565      Skype: jane_curry_uk
Email: jane.curry@skills-1st.co.uk   Web: http://www.skills-1st.co.uk
Copyright (c) 2015 Jane Curry < jane.curry@skills-1st.co.uk >.  All rights reserved.

**Comment by paericksen** [comment]
I have a pair of TH3030S in my lab, and I might could scrounge up an old pair of AX3400(?) if needed.

**Comment by jcurry** [comment]
Hi Andy,
I have cut a version of the A10 ZenPack for Zenoss 3.2.1.  You can find 
the code here - https://github.com/jcurry/ZenPacks.community.A10 .  I 
have added an egg file for Zenoss 3.2.1 simply by recompiling the code 
in a 3.2.1 environment.

I must stress that all I have done is install this code - I don't have 
any A10 devices accessible from my Zenoss 3 rig so you should definitely 
try this in a test environment.

I would also suggest that you install the ZenPack in dev mode in case 
you need to tweak things - instructions in the README.

Please provide feedback.

Cheers,
Jane

On 12/05/15 18:39, Andy Ericksen wrote:

> I have a pair of TH3030S in my lab, and I might could scrounge up an 
> old pair of AX3400(?) if needed.
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/jcurry/ZenPacks.community.A10/issues/1#issuecomment-101361428.

## 

Zenoss Master, Tivoli Certified Consultant & Instructor
Skills 1st Limited, 2 Cedar Chase, Taplow, Bucks, SL6 0EU, UK.
Registered in England & Wales, Company No. 3458854.
Tel: +44 (0)1628 782565      Skype: jane_curry_uk
Email: jane.curry@skills-1st.co.uk   Web: http://www.skills-1st.co.uk
Copyright (c) 2015 Jane Curry < jane.curry@skills-1st.co.uk >.  All rights reserved.

**Comment by paericksen** [comment]
the zenpack seems to install correctly now in my lab on version 3.2.1.  Thanks a bunch!
