### ISSUE TITLE
components not displayed in UI

### ISSUE THREAD

**Issue by paericksen** [jcurry/ZenPacks.community.A10#3]
on my lab zenoss v3.2.1, after adding a device and assigning the modeler plugins, the component types (Service Groups, Servers, Interfaces, Virtual Servers) are listed in the menu on the left, but selecting a component type does not display those components on the right side content panel, the display drop down is also empty.

![capture](https://cloud.githubusercontent.com/assets/4397404/7705512/9f462d00-fe12-11e4-85bc-2c56c1a9adcb.PNG)

**Comment by paericksen** [comment]
well this is interesting, I removed the zenpack, removed the perf folders and re-installed the zenpack and now the components are there.

**Comment by paericksen** [comment]
okay even more interesting, the components are no longer visible

**Comment by paericksen** [comment]
not sure if it's related but zenperfsnmp is showing some warnings for the a10:

```
2015-05-19 16:40:37,648 WARNING zen.zenperfsnmp: Error reading value for "Management Interface 0" on lab-a10-lb01 (oid .1.3.6.1.2.1.31.1.1.1.10 is bad)
2015-05-19 16:40:37,648 WARNING zen.zenperfsnmp: Error reading value for "Management Interface 0" on lab-a10-lb01 (oid .1.3.6.1.2.1.31.1.1.1.11 is bad)
2015-05-19 16:40:37,678 WARNING zen.zenperfsnmp: Error reading value for "Management Interface 0" on lab-a10-lb01 (oid .1.3.6.1.2.1.2.2.1.14 is bad)
2015-05-19 16:40:37,684 WARNING zen.zenperfsnmp: Error reading value for "Management Interface 0" on lab-a10-lb01 (oid .1.3.6.1.2.1.2.2.1.20 is bad)
2015-05-19 16:40:37,700 WARNING zen.zenperfsnmp: Error reading value for "Ethernet 2" on lab-a10-lb01 (oid .1.3.6.1.2.1.31.1.1.1.11.2 is bad)
2015-05-19 16:40:37,714 WARNING zen.zenperfsnmp: Error reading value for "Management Interface 0" on lab-a10-lb01 (oid .1.3.6.1.2.1.31.1.1.1.6 is bad)
2015-05-19 16:40:37,714 WARNING zen.zenperfsnmp: Error reading value for "Management Interface 0" on lab-a10-lb01 (oid .1.3.6.1.2.1.31.1.1.1.7 is bad)
2015-05-19 16:40:37,736 WARNING zen.zenperfsnmp: Error reading value for "LAB_IMS_DNS" on lab-a10-lb01 (oid .1.3.6.1.4.1.22610.2.4.3.3.4.1.1.11.11.76.65.66.95.73.77.83.95.68.78.83 is bad)
2015-05-19 16:40:37,742 WARNING zen.zenperfsnmp: Error reading value for "LAB_DNS" on lab-a10-lb01 (oid .1.3.6.1.4.1.22610.2.4.3.3.4.1.1.11.7.76.65.66.95.68.78.83 is bad)
2015-05-19 16:40:37,756 WARNING zen.zenperfsnmp: Error reading value for "LAB_ENUM" on lab-a10-lb01 (oid .1.3.6.1.4.1.22610.2.4.3.3.4.1.1.11.8.76.65.66.95.69.78.85.77 is bad)
```

**Comment by paericksen** [comment]
Is there any more information I can provide to help with trouble shooting this issue?

**Comment by jcurry** [comment]
Hi Andy,
Suspect nothing will happen with this for a week or so - I have a poorly 
Mum at the moment.  Please bear with me.

Cheers,
Jane
On 26/05/15 18:14, Andy Ericksen wrote:

> Is there any more information I can provide to help with trouble 
> shooting this issue?
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/jcurry/ZenPacks.community.A10/issues/3#issuecomment-105607435.

## 

Zenoss Master, Tivoli Certified Consultant & Instructor
Skills 1st Limited, 2 Cedar Chase, Taplow, Bucks, SL6 0EU, UK.
Registered in England & Wales, Company No. 3458854.
Tel: +44 (0)1628 782565      Skype: jane_curry_uk
Email: jane.curry@skills-1st.co.uk   Web: http://www.skills-1st.co.uk
Copyright (c) 2015 Jane Curry < jane.curry@skills-1st.co.uk >.  All rights reserved.

**Comment by jcurry** [comment]
First thing to do is make sure you have cleared the browser cache.

Sounds like the left-hand menu suggests you DO have components but they don't actually display?
Suggest you use the Zope Management Interface (ZMI) to check whether the OBJECTS really exist - point your browser at your zenoss /zport/dmd/manage eg. zen42.class.example.org:8080/zport/dmd/manage.  You should be able to drill into the device class, down devices, pick an instance and then drill into the component types and component instances.  If this shows that you really do have virtual server and service group instances, then we have a GUI issue, probably in the javascript file.

Can you run the Error Console for your browser when you navigate to one of these "missing" components, and look for errors.  Better still run a Firebug Web Console.  Unfortunately, Zenoss does tend to generate heaps of lower-level errors in these consoles so you need to focus on critical errors - always worth checking the last few lines of such console output.

Cheers,
Jane

**Comment by paericksen** [comment]
> First thing to do is make sure you have cleared the browser cache.

Done, I've also tested with Firefox, Chrome, and IE.  All display the same symptoms.

> Sounds like the left-hand menu suggests you DO have components but they don't actually display?
> Suggest you use the Zope Management Interface (ZMI) to check whether the OBJECTS really exist - point your browser at your zenoss /zport/dmd/manage eg. zen42.class.example.org:8080/zport/dmd/manage. You should be able to drill into the device class, down devices, pick an instance and then drill into the component types and component instances. If this shows that you really do have virtual server and service group instances, then we have a GUI issue, probably in the javascript file.

The components do exist, for example `/zport/dmd/Devices/Network/A10/devices/lab-a10-lb01/a10Servers` contains six different real servers.  I confirmed a10Servers, a10ServiceGroups, and a10VirtualServers all contain 'correct' objects.

> Can you run the Error Console for your browser when you navigate to one of these "missing" components, and look for errors. Better still run a Firebug Web Console. Unfortunately, Zenoss does tend to generate heaps of lower-level errors in these consoles so you need to focus on critical errors - always worth checking the last few lines of such console output.

There are many ReferenceErrors, but nothing jumps out at me.  The last few when changing from one component link to another are:

```
13:46:51.111 ReferenceError: reference to undefined property this.layout ext-all.js:7:151506
13:46:51.111 ReferenceError: reference to undefined property this.buttons ext-all.js:7:198938
13:46:51.111 ReferenceError: reference to undefined property d.destroy ext-base.js:7:7836
13:46:51.112 ReferenceError: reference to undefined property this.removeMode ext-all.js:7:123661
13:46:51.112 ReferenceError: reference to undefined property this.innerHd ext-all.js:11:141152
13:46:51.112 TypeError: Ext.fly(...) is null ext-all.js:11:141152
```

Here's a Gist of Firebug console from a page refresh: https://gist.github.com/paericksen/20f3317ba20471d00708

**Comment by jcurry** [comment]
I have just built a new version of this ZenPack for Zenoss 3 on a slightly later version of Zenoss.  I have also created a Zenoss3 branch for this repository.  Could you have a go with the new version and report back?
Thanks,
Jane

**Comment by paericksen** [comment]
I'm sad to say that the new version 1.0.3 for Zenoss3 does not correct my issue.

I removed the A10 from zenoss, and then removed the zenpack.  

I renamed the zenpack folder to .old and then `git cloned` the repo again.  

Then `git checkout Zenoss3`, cd into it and `zenpack --link --install ./`

I then added the A10 in Zenoss and added the A10 modeler plugins, saved, and modeled.  The components still do not show up.

**Comment by jcurry** [comment]
Thanks for trying.  It was a bit of a long shot that the javascript 
libraries might have changed.  Any chance that you have a test 
environment that I could access that is monitoring a test A10???

Cheers,
Jane

On 12/06/15 14:55, Andy Ericksen wrote:

> I'm sad to say that the new version 1.0.3 for Zenoss3 does not correct 
> my issue.
> 
> I removed the A10 from zenoss, and then removed the zenpack.
> 
> I renamed the zenpack folder to .old and then |git cloned| the repo 
> again.
> 
> Then |git checkout Zenoss3|, cd into it and |zenpack --link --install ./|
> 
> I then added the A10 in Zenoss and added the A10 modeler plugins, 
> saved, and modeled. The components still do not show up.
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/jcurry/ZenPacks.community.A10/issues/3#issuecomment-111500706.

## 

Zenoss Master, Tivoli Certified Consultant & Instructor
Skills 1st Limited, 2 Cedar Chase, Taplow, Bucks, SL6 0EU, UK.
Registered in England & Wales, Company No. 3458854.
Tel: +44 (0)1628 782565      Skype: jane_curry_uk
Email: jane.curry@skills-1st.co.uk   Web: http://www.skills-1st.co.uk
Copyright (c) 2015 Jane Curry < jane.curry@skills-1st.co.uk >.  All rights reserved.

**Comment by paericksen** [comment]
I think I can arrange that, how would you like me to communicate the access info?

**Comment by paericksen** [comment]
fix looks good as far as I can tell.  the UI elements all seem to be in the right place now.  Thanks,
