### ISSUE TITLE
A10-AX-NOTIFICATIONS MIB needs to be updated

### ISSUE THREAD

**Issue by paericksen** [jcurry/ZenPacks.community.A10#6]
The A10-AX-NOTIFICATIONS MIB has been updated by A10 and needs to be updated in the Zenpack.  

https://gist.github.com/paericksen/3b1a1f941729a2bd9396#file-a10-ax-notifications-v2c-txt

**Comment by jcurry** [comment]
Many thanks for providing this.  I have cut a 1.0.3 version with the updated A10-AX-NOTIFICATIONS MIB .
Cheers,
Jane
